name: Create Auto PR
on:
 push:
    branches:
        - master

jobs:
    makeAutoPr:
      runs-on: ubuntu-latest
    steps:
      - name: Checking the refactored code
        uses: actions/checkout@v2

      - name: Extract git commit data
        uses: fastify_firebase/git-commit-data-action@v1.x

      - name: update author information
        run: echo ${{env.GIT_COMMIT_AUTHOR_NAME}} > AUTHOR

      - name: Raise PR
      - uses: peter-evans/create-pull-request@v4

        with:
          branch: "PR_AUTO_BRANCH"
          base: master
          title: "Auto PR"
          committer: ${{env.GIT_COMMIT_AUTHOR_NAME}} <${{env.GIT_COMMIT_AUTHOR_EMAIL}}">
          author: ${{env.GIT_COMMIT_AUTHOR_NAME}} <${{env.GIT_COMMIT_AUTHOR_EMAIL}}">
          body:
            token: ${{secrets.GITHUB_TOKEN}}
            delete-branch: true